name: CI-user-app

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "apps/user/**"
      - "packages/**"
      - "package.json"
      - "yarn.lock"
      - ".github/workflows/**"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    # Optional:
    #   Only consider those files/paths to trigger the github action
    #   to prevent unnecessary builds.
    paths:
      - "apps/user/**"
      - "packages/**"
      - "package.json"
      - "yarn.lock"
      - ".github/workflows/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Why not using setup-node 2.2+ cache option (yet) ?
      # see https://github.com/belgattitude/nextjs-monorepo-example/pull/369
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-folder-

      # see https://github.com/vercel/next.js/pull/27362
      - name: Restore nextjs build user-app from cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/apps/user/.next/cache
          key: ${{ runner.os }}-user-app-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('apps/user/src/**.[jt]sx?', 'apps/user/src/**.json') }}
          restore-keys: |
            ${{ runner.os }}-user-app-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        run: |
          yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Typecheck
        working-directory: apps/user
        run: |
          yarn typecheck

      - name: Linter
        working-directory: apps/user
        run: |
          yarn lint --cache

      - name: Unit tests
        working-directory: apps/user
        run: |
          yarn test

      - name: Build app
        working-directory: apps/user
        run: |
          yarn build
        env:
          # Speed up build: they are linted in a previous step
          NEXTJS_IGNORE_ESLINT: 1
          # Speed up build: they are typechecked in a previous step
          NEXTJS_IGNORE_TYPECHECK: 1
          # Speed up build: don't run if not needed, enable if it becomes needed
          NEXT_DISABLE_SOURCEMAPS: 1
          # Don't send telemetry for ci
          NEXT_TELEMETRY_DISABLED: 1

      - name: Check bundle size
        working-directory: apps/user
        run: |
          yarn bundle:check-size
