name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Why not using setup-node 2.2+ cache option (yet) ?
      # see https://github.com/belgattitude/nextjs-monorepo-example/pull/369
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-folder-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build i18n
        run: |
          yarn build:i18n

      - name: Linter
        run: |
          yarn lint --cache

      - name: Unit tests
        run: |
          yarn test

      - name: Build
        run: |
          yarn build:packages
          yarn build:apps
        env:
          # Speed up build: they are linted in a previous step
          NEXTJS_IGNORE_ESLINT: 1
          # Speed up build: they are typechecked in a previous step
          NEXTJS_IGNORE_TYPECHECK: 1
          # Speed up build: don't run if not needed, enable if it becomes needed
          NEXT_DISABLE_SOURCEMAPS: 1
          # Don't send telemetry for ci
          NEXT_TELEMETRY_DISABLED: 1
