name: Deploy Storybook

on:
  push:
    branches:
      - main
    paths: ["src/ui/**", "src/apps/**"]
jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run i18n:build
      - run: npm run sb:build
      - run: touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
          target_folder: storybook
          clean: true
